name: News Sender

on:
  schedule:
    # ⏰ Runs automatically every 15 days at midnight UTC
    - cron: '0 0 */15 * *'
  workflow_dispatch:

permissions:
  contents: write  # Allow pushing changes

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Firebase script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python firebase.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main  # ✅ Always sync with latest changes before pushing
          git add .
          git commit -m "Update news data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
